---
title: "Report Data-Mining-FS-2026"
author: "S. Lindegger"
date: "2026-03-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data Mining for the Social Sciences using R Term: Spring 2026 

This report is divided into two parts. First, it will describe the original academic outline of the project and idea. Additionally, as issues were encountered during the project work, it will also explain the shift of the academic direction, as the original focus of this project was data mining rather than academic research and data gathering. Secondly, this report describes the project work, the challenges and limitations encountered during the progress. 

## Introduction of the Project 
The idea to assess security issues in the election or voting process started when I attended the Dutch general elections in October 2025 as an international observer working for an NGO. I started to consider how certain security issues are addressed in Switzerland, as from my perspective, voting by letter is a very popular method. However, the security of democracy is also threatened through various other aspects. One of which is modern technology, the spread of misinformation and the manipulation of public opinion (Inter-Parliamentary Union, 2022). In particular the use of social media is a driver of this development, with the most prominent example being Russia’s interference with the 2016 US elections (McKay and Tenove, 2020). 

This resulted in the following research questions: 

RQ1: How has discourse about election/procedures evolved? 

RQ2: How are threats to democracy (e.g. foreign interference, disinformation campaign, inclusiveness to election/voting processes) addressed? 

Due to data gathering issues, which are explained in detail in the second part of this report, the research questions have been adapted and kept rather broad. 

RQ3: What are the security issues regarding Swiss democracy discussed in parliament? RQ4: How frequent are security issues regarding Swiss democracy discussed in parliament? 

To answer the research questions in detail, more literature would need to be consulted as well as more data gathered with a sturdier process. These issues are addressed in the second part. However, in short, out of the parliamentary affairs considered, less than 5% of affairs included issues on democracy. Additionally, of these affairs about 12% addressed security issues namely, international security/military, migration, parliamentary control, finance/corruption, and social security. However, this analysis was conducted on a random sample size with no methodological considerations and are thus, very limited in their meaning. 

## Project Progress 
The second part of this report assesses the data sources, challenges encountered and the limitations of this project.  

### Data
The original idea to access the required data was to use the Swiss parliament’s website as well as the Swiss federal court’s website to assess which security issues regarding election and voting processes have been discussed and if there is a judicial ruling. However, the scope was narrowed down due to time limitations and difficulties encountered when accessing the parliament’s website. 

The data source used for this project is https://ws-old.parlament.ch/ . It is noteworthy that this webpage states that it is the “old” version. However, this Open Data API is provided on the official parliament’s website www.parlament.ch, thus it is assumed that web scraping should be done there.  

### Scraping
The original idea was to evaluate which affairs address election/voting aspects and then use AI to evaluate potential security issues. To narrow down the affairs considered, affairs were assessed if they addressed democracy issues, in order to have a broader base. 

Due to the set up of the API, the scraping process included the following steps: 

1. Access ID of all parliamentary affairs available on the API 

2. Using the affair ID’s tobuild a loop to access title and keyword information of affairs 

As a side note, the parliamentary affairs visible on the website did not include the actual text of the affairs that what proposed to parliament. Thus, during step two, the accessed keywords were evaluated (using AI: Claude) to evaluate which affairs address democracy issues. The first step rendered 65’750 affair IDs. The second step had to be limited to 5’000 affair’s title and keywords. This issue is addressed in challenges further down the report. Of these 5’000 affairs, 239 were identified as addressing democracy issues. 

3. Using the affair ID’s of the identified democracy affairs, the text is gathered using a for loop. 

This was the original idea on how to scrape the website. However, as the 239 affairs did not render any text, due to error 404 encountered, the project needed to be adapted. Rather than using AI to text evaluate the 239 affair’s text, AI was used to evaluate security issues based on the title and provided keywords. This allowed the findings provided in the first section. 

### Challenges and Limitations 
As mentioned before, this project did not render the expected results and thus, needed major adaptations. Thus, the challenges encountered go hand in hand with the limitations of this project. Here are the key issues: 

1. Firstly, the project had to be restarted, because of a misunderstanding regarding the website’s API key. The website did not require an API key, but this was not clear from the beginning. Because it did not need an API key, I never received one. This led to the creation of an artificial API key, which ended up being pushed on the Github respo. As publishing API keys (even fake one’s) is not good coding practise as it is an issue with data privacy, the decision was made to delete the first Github repo and restart. The work conducted until that point was copy-pasted to the new Github respo meaning that it does not allow to show any comments on how the first steps were built. However, this issue helped me to adequately handle the API key to connect the LLM Claude to the project later. Thus, lessons learned from the previous mistake were directly applied. 
 

2. Originally, the idea was to scrap the parliament website as well as the federal court’s website. Essentially, the parliament website is scraped three times as explained in the subchapter “Scraping”. It has been more time intensive than expected for two main reasons. Firstly, this is my first time conducting a scraping project, therefore, the progress was more time intensive due to lessons learned. Secondly, scraping the keywords has taken multiple hours, and the total of 65’750 affairs were never scraped, as the loop got stuck.  An LLM was consulted, the suggestion was to add a component that saves every 100 accessed affair and to continue from the last one if the scraping crashed. However, as this assignment focuses on the scraping part rather than the actual data gathered, the decision was made to focus on the first 5’000 affairs scraped. Thus, rather than focusing on two websites and 65’750 affairs, this project focuses on one website and 5’000 affairs, in order to simply scale it down. However, as the code is working, the reproducibility is given, with a potential adjustment suggested by LLM of saving affairs and restarting from the last affair gathered, to ensure all the affairs can be accessed. 
 

3. After drawing all the keywords from the website, approximately 3'000 different keywords were received. These keywords can be assigned freely to the affair. Thus, the evaluation of the relevant affairs is clearly limited, as the assignment of keywords lacks a methodological base.  In order to evaluate keywords, the list of all words was given to an LLM (Claude) for assessment. It was interesting to understand how LLM assess the issue and rendered keywords related to democracy. This also enhanced efficiency, compared to assessing them manually. This narrowed down the list of affairs to 239. 
 

4. The text of these given 239 affairs should have been scrapped, however, all of them rendered an error 404. It is assumed, because only the first 5’000 affairs were scraped, that these were the oldest affairs and their text is not published (anymore) on the website. This is a simple logical assumption but not further investigated. It seems as if the code/for looped functioned, but the website is just not offering the information anymore. A trial was made to access more recent affairs, that was successful. However, this only focused on few single cases, to check the thought process. Thus, as the text of the affairs could not been accessed, it was decided to use LLM to text analyse the title and the keywords of the 239 affairs, of which the data was already obtained.  

Here of course a working solution might have been to use the affair ID’s to directly access the affair’s text and avoiding the extra step of evaluating keywords to narrow down the search. This might have worked but it would have been a requirement to scrap a lot of data that was not necessary and that was not used. So, it is questionable if this would have been good coding practise and if it would be polite to do so. Additionally, the scraping of the affair’s title and keywords was already time consuming and difficult due to the data volume. It can be assumed that scraping all the affair’s text would have required additional coding components to ensure a smooth scraping process.  

This also allows a reflection of the scalability and reproducibility of the code provided in this project. It clearly demonstrated the limits of amount of data scraped. The first trial of accessing all title/keywords crashed around 9’700 affairs. Thus, this leaved the conclusion that the code is reproducible and functioning, but to scale it to higher numbers, other coding-features, as mentioned above are required. 

5. The last step in the evaluation process of assessing the affairs regarding security issues was to analyse the title and keywords obtained. Here, the data input was very limited and did not allow a full understanding of what an affair was addressing, with titles like “Bericht der Kommission vom 12.12.1990” (Parlament.ch, 2024, losely translated to “Report of the commission”) just to name one example. Thus, again an LLM (Claude) was consulted in analysing the security issues of the 239 affairs addressing democracy. At this point, the research focused switched to simply assess security issues in affairs addressing democracy rather than additionally narrowing down the data base to election and voting process, as the given information was too scarce.  

The LLM rendered security issues, some of them were in English and some of them in German. Additionally, the same keyword issue as before, with the random assigning of words arose. Thus, summarising them cohesively was required. If this assignment did not focus on data mining but the data obtained, it would have been sensible to assess security themes in the literature review and then apply them directly to the affairs, in order to receive a more sensible outcome. However, this also shows the limitations of LLMs working methodologically. Of course, the prompt was kept rather generic, which was interesting to see, how LLM ‘s handles these situations. 

## Conclusion
To conclude, even though the project rendered some data, to adequately answer the research question several steps would need to be taken. Firstly, a sturdy literature review is required to ground the keywords, evaluation process and findings in theory. Additionally, to ensure stability of the code, additional safety features to ensure smooths scraping such as automatic saving of scraped data and the continuity of the scraping process are required. This also increased the time intensity of the project but does not solve the methodological issues that arose with the keyword assignment of the affairs.

## LLM Disclaimer 
LLMs (namely Claude, Perplexity, Chatgpt) were used in this project. LLMs have been used to generate and debug code. Also, rather than trying out code in RStudio directly to see what happens, code was suggested directly to LLM to generate a base of which to work of. The aim discussion solutions with the LLM was to avoid trying bugged code on an external website, without fully understanding what is happening but also to drive the ideas rather than relying on LLMs input on problem solving.  

Additionally, LLMs were used to as a guide on how to use Github (e.g. how to create an issue), as an efficient research tool (e.g. to evaluate which responsibilities the federal court carries compared to the federal administrative court), to evaluate the list of keywords, and to verify privacy settings and to try to avoid pushing sensitive information to Github. 

Generally, LLMs were used responsibly, with the aim of supporting efficient learning.  

 ## Bibliography
 Inter-Parliamentary Union. (2022).*How to mitigate these five threats to democracy.* [online] Available at: https://www.ipu.org/news/news-in-brief/2022-09/how-mitigate-these-five-threats-democracy. 

McKay, S. and Tenove, C. (2020). Disinformation as a Threat to Deliberative Democracy.*Political Research Quarterly,* 74(3), p.106591292093814. doi:https://doi.org/10.1177/1065912920938143. 

‌‌Parlament.ch. (2024).*Initiatives parlementaires. Délais d’examen - Web Services of the Swiss Parliament.* [online] Available at: https://ws-old.parlament.ch/affairs/19890251 [Accessed 22 Mar. 2026]. 
